//Iniciar sesion
export const INICIAR_SESION_START = 'INICIAR_SESION_START'
export const INICIAR_SESION_ERROR = 'INICIAR_SESION_ERROR'
export const INICIAR_SESION_EXITO = 'INICIAR_SESION_EXITO'

// Registro
export const REGISTRO_USUARIO_START = 'REGISTRO_USUARIO_START'
export const REGISTRO_USUARIO_ERROR = 'REGISTRO_USUARIO_ERROR'
export const REGISTRO_USUARIO_EXITO = 'REGISTRO_USUARIO_EXITO'

//Get Size of Pets
export const GET_PET_SIZE = 'GET_PET_SIZE'

//Save Pet Form
export const SAVE_PET_FORM_ACTION = 'GET_PET_FORM_ACTION'