//Iniciar sesion
export const INICIAR_SESION_START = 'INICIAR_SESION_START'
export const INICIAR_SESION_ERROR = 'INICIAR_SESION_ERROR'
export const INICIAR_SESION_EXITO = 'INICIAR_SESION_EXITO'

// Registro
export const REGISTRO_USUARIO_START = 'REGISTRO_USUARIO_START'
export const REGISTRO_USUARIO_ERROR = 'REGISTRO_USUARIO_ERROR'
export const REGISTRO_USUARIO_EXITO = 'REGISTRO_USUARIO_EXITO'

//Get Size of Pets
export const GET_PET_SIZE_DATA = 'GET_PET_SIZE_DATA'

//Save Size Pet selected
export const SMALL_SIZE_PET_ACTION = 'SMALL_SIZE_PET_ACTION'
export const MEDIUM_SIZE_PET_ACTION = 'MEDIUM_SIZE_PET_ACTION'
export const BIG_SIZE_PET_ACTION = 'BIG_SIZE_PET_ACTION'